In [1]:
import pandas as pd

In [2]:
qg = pd.read_csv("query_generation.csv")

In [3]:
qg.head()

,Topic,FeedbackType,IsOutlier,OutlierId,DSATTopicId,DSATTopicTitle,Intent,IntentDescription,TaskTypes,Domains,DataSources,OutputForms,Queries,OriginalTimestamps
0,0,ThumbsUp,False,NaN,-1,NaN,Orientación sobre fondos INNVIERTE DEEP START,El usuario busca orientación sobre cómo articu...,"[""Research""]","[""Business / finance / markets"", ""Technical / ...","[""Web + work content""]","[""Freeform text""]","[""Trabajo en el área de Desarrollo de negocio ...","[""2026-05-22T12:24:01.845Z""]"
1,0,ThumbsDown,False,NaN,16,Execution Incompletion,Funding round assessment email,The user wants an analyst-style email assessme...,"[""Draft content"", ""Compare""]","[""Business / finance / markets""]","[""Work content""]","[""Freeform text""]","[""Imagine you are an analyst asked to assess t...","[""2026-05-11T01:05:55.312Z""]"
2,0,ThumbsUp,False,NaN,-1,NaN,Book review and summary,The user is requesting a review and summary of...,"[""Research"", ""Summarize""]","[""General work""]","[""Web only""]","[""Freeform text""]","[""Please give me a review of the book Weapons ...","[""2026-05-27T14:34:58.378Z""]"
3,0,ThumbsDown,False,NaN,18,Factual Incorrectness / Entity Confusion,Count integrations using assignment status,The user wants to know how many integrations c...,"[""Research""]","[""Technical / IT / M365 / tools""]","[""Work content""]","[""Freeform text""]","[""How many <PII> integrations consumes \""assig...","[""2026-05-28T16:43:22.254Z""]"
4,0,ThumbsUp,False,NaN,-1,NaN,Identify 1970s young adult book,The user is seeking the title and author of a ...,"[""Research""]","[""General work""]","[""Web only""]","[""Freeform text""]","[""i read a book in the 1970s for young adults....","[""2026-06-03T14:41:20.644Z""]"

In [4]:
qg.shape

(1256, 14)

In [5]:
import ast

total_query_count = 0
query_list = []
query_list_time = []

for index, row in qg.iterrows():
    queries = ast.literal_eval(row["Queries"])  # convert string → list
    OriginalTimestamps = ast.literal_eval(row["OriginalTimestamps"])  # convert string → list
    # print(queries)
    # print(type(queries))
    # print(len(queries))
    # print(queries[0])
    # break
    total_query_count += len(queries)
    query_list_time.extend(OriginalTimestamps)
    query_list.extend(queries)

In [6]:
total_query_count

1256

In [7]:
query_list[:10]

['Trabajo en el área de Desarrollo de negocio de tecnología. Estamos valorizando una serie de desarrollos de Deep Tech en torno a TRL 4 que el negocio no quiere seguir escalando ni invirtiendo porque no ser estratégicos. Mi directora nos ha dicho que miremos los fondos del CDTI, en concreto del programa INNVIERTE DEEP START. Te adjunto <File> y <Email> varios para que me orientes como articular la gestión. La idea es obtener financiación para seguir escalando la tecnología.',
 "Imagine you are an analyst asked to assess the latest round of the <Project> funding (Series H) - attached IC memo for Series H and Series G for reference (Series G is the January 2026 memo and Series H is titled '<Project> IC Memo'). Write an email assessment similar to the Series G email assessment (<File> attached). Ask me any questions that will help you complete this task.",
 'Please give me a review of the book Weapons of Math Destruction and main points.',
 'How many <PII> integrations consumes "assignment status" in Oracle?  Source: <PII> Sharepoint sites',
 'i read a book in the 1970s for young adults. it included something about tripods, and the main character had a tracking device in his body. i cannot remember the name of the book or the author',
 'Where was UL94 mentioned in <File>',
 'is max 300V stabilizer wont affect the AC compressor.',
 'please, summarize his slide deck useing the scheme Question Cost Solution to summarize this slide. It should be something that hits their pain point directly. like a question like this: "How many of you ....? " then name the cost of that problem: "that means that .... " the cost, Then position myself as the solution provider. " I am going to show you... " Try to put in focus the use of COPILOT M365 in the center of the scheme. Don´t extend too much. 50 words should be enough',
 'I would like to understand if the <PII> in conjunction with <PII> utilises the ability to make bulk instant payments under the requirements of sepa instant',
 'Can you help me find customer contacts using linkedin and persona types as indicated by my own internal <File>?']

In [8]:
query_list_time[:10]

['2026-05-22T12:24:01.845Z',
 '2026-05-11T01:05:55.312Z',
 '2026-05-27T14:34:58.378Z',
 '2026-05-28T16:43:22.254Z',
 '2026-06-03T14:41:20.644Z',
 '2026-06-04T20:39:02.051Z',
 '2026-05-14T16:16:04.635Z',
 '2026-05-19T06:30:13.320Z',
 '2026-05-15T09:36:18.740Z',
 '2026-06-04T08:13:57.821Z']

In [10]:
df = pd.read_parquet("dsat_classification.parquet", engine="pyarrow")
df.head()

,ClientCountry,ConversationId,CopilotExtensionIds,CustomerExperienceSyndrome,FeedbackPolarity,FeedbackType,IsVerbal,PromptLanguage,RequestTime,RowKeyId,TurnIndex,topic_explanation,topic_id,topic_prob,topic_summary,topic_theme,topic_title
0,United States,00518a01-ee3c-472e-a0e9-007028b999c0,[P_552e6eda-fc18-7fb9-0ef6-1bf2de3393e4],“Tabular Anxiety Syndrome”: Cannot work/format...,negative,ThumbsDown,True,English,2026-05-13T20:50:35.314Z,4e92d439-afc7-4f8d-b9b8-c39ae9dca68b,9.0,The user reports that the text in the PDF appe...,24,0.90,Researcher produces malformed tables or struct...,User intent understanding,Structured Output / Schema Failure
1,United Kingdom,00ab3f19-277b-472a-a9d5-c9c34aef26cd,[P_552e6eda-fc18-7fb9-0ef6-1bf2de3393e4],“Almost helpful Syndrome”: Incomplete Answers,negative,ThumbsDown,False,English,2026-05-11T01:05:55.312Z,d2aeccb6-fb29-41ad-967e-f6ed71793e41,2.0,The agent repeats the user's instructions and ...,16,0.85,Researcher understands the task but does not c...,Response quality,Execution Incompletion
2,United Kingdom,00ab3f19-277b-472a-a9d5-c9c34aef26cd,[P_552e6eda-fc18-7fb9-0ef6-1bf2de3393e4],“Attachment Syndrome”: Fails with Attachments,negative,ThumbsDown,False,English,2026-05-11T01:31:20.680Z,36387067-02c7-4723-ac45-f67eb53efd21,4.0,The user provided attached files (Series G and...,17,0.95,Researcher fails to read or correctly use atta...,Response quality/Reliability,Attachment Handling Failure
3,United Kingdom,00ab3f19-277b-472a-a9d5-c9c34aef26cd,[P_552e6eda-fc18-7fb9-0ef6-1bf2de3393e4],“Tabular Anxiety Syndrome”: Cannot work/format...,negative,ThumbsDown,True,English,2026-05-11T01:43:54.027Z,c1ef1a95-b0e7-4141-b9cf-55d8a032070d,5.0,The user complains about 'random bolding of te...,24,0.70,Researcher produces malformed tables or struct...,User intent understanding,Structured Output / Schema Failure
4,United States,00f87c3f-ce80-41ce-915a-ccf98a799369,[P_552e6eda-fc18-7fb9-0ef6-1bf2de3393e4],“Almost helpful Syndrome”: Incomplete Answers,negative,ThumbsDown,True,English,2026-05-18T16:18:55.724Z,cb770b3b-d15c-41f2-8f9b-92fca740baf0,23.0,The user states that the prompt contained mult...,16,0.95,Researcher understands the task but does not c...,Response quality,Execution Incompletion

In [11]:
df.shape

(3782, 17)

In [12]:
df["ConversationId"].value_counts()

ConversationId
83949feb-4f39-4eb3-9b8b-1ec8960db715    11
2cbff65a-58c9-4ed3-b15b-2e348da71320     8
ddf588ed-b146-47b2-9a98-f26d2f22f610     8
0ca86543-478b-4f81-9bb7-86424723a318     8
7f9a3ea2-d334-482d-a193-e15f721c7586     7
                                        ..
06f40de1-6564-40a1-b4a3-2448ff854ae2     1
06f679cc-3626-4409-ad13-7edd259b099f     1
071f2368-d835-4552-b663-a093cbbe8e5b     1
07224700-0b68-4907-9f90-d65a6a39213f     1
fffa9ff3-4929-427b-ae14-660389cf8a6f     1
Name: count, Length: 3038, dtype: int64